# Generated by Django 3.2.12 on 2024-04-06 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dh_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='Student',
        ),
    ]
