# Generated by Django 3.2.12 on 2024-04-09 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dh_user', '0003_student_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_code',
            new_name='username',
        ),
    ]
