# Generated by Django 3.2.12 on 2024-06-13 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dh_user', '0005_auto_20240501_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='collage_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
