# Generated by Django 3.2.12 on 2024-06-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dh_user', '0006_student_collage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email_otp',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
