# Generated by Django 3.2.12 on 2024-06-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dh_user', '0007_student_email_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
