# Generated by Django 3.2.12 on 2024-04-06 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=100, null=True)),
                ('level', models.IntegerField(unique=True)),
                ('description', models.TextField(default='')),
                ('status', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='GamesOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(default='')),
                ('status', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='GameUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(default='')),
                ('status', models.CharField(choices=[('C', 'Completed'), ('O', 'Open'), ('Failed', 'Failed')], max_length=50, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.games')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='games',
            name='options',
            field=models.ManyToManyField(blank=True, to='games.GamesOptions'),
        ),
    ]
