# Generated by Django 3.2.12 on 2024-04-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameuser',
            name='status',
            field=models.CharField(choices=[('C', 'Completed'), ('O', 'Open'), ('F', 'Failed')], max_length=50, null=True),
        ),
    ]
