# Generated by Django 3.2.12 on 2024-05-12 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_gameuser_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamesType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(default='')),
                ('status', models.BooleanField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='games',
            name='options',
            field=models.ManyToManyField(blank=True, null=True, to='games.GamesOptions'),
        ),
        migrations.AlterField(
            model_name='games',
            name='tittle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gamesoptions',
            name='tittle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='games',
            name='game_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.gamestype'),
        ),
    ]
