# Generated by Django 3.2.12 on 2024-05-12 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20240512_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='options',
            field=models.ManyToManyField(blank=True, to='games.GamesOptions'),
        ),
    ]
