# Generated by Django 3.2.12 on 2024-05-29 01:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_games_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='mode',
            field=models.CharField(choices=[('options', 'Options'), ('qr', 'QR Code'), ('image', 'Image Upload')], default='qr', max_length=50),
        ),
        migrations.AddField(
            model_name='games',
            name='qr_code',
            field=models.FileField(default='', upload_to='game-uploads'),
        ),
        migrations.CreateModel(
            name='UserUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(default='', upload_to='user-uploads')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('profile', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='games.gameuser')),
            ],
        ),
    ]
