# Generated by Django 3.2.12 on 2024-05-29 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20240529_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='qr_code',
            field=models.FileField(blank=True, default='', null=True, upload_to='game-uploads'),
        ),
    ]
