# Generated by Django 3.2.12 on 2024-05-30 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_alter_games_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='qr_value',
            field=models.TextField(default=''),
        ),
    ]
