# Generated by Django 3.2.12 on 2024-06-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_alter_games_qr_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='collage_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
