# Generated by Django 3.2.12 on 2024-06-15 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_games_collage_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='games',
            old_name='qr_value',
            new_name='answer_value',
        ),
    ]
