# Generated by Django 3.2.12 on 2024-06-15 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_rename_qr_value_games_answer_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameuser',
            name='answer_value',
            field=models.TextField(default=''),
        ),
    ]
