# Generated by Django 3.2.12 on 2024-06-17 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_gameuser_answer_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userupload',
            name='profile',
        ),
    ]
