# Generated by Django 3.2.12 on 2024-06-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_remove_userupload_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameuser',
            name='status',
            field=models.CharField(choices=[('C', 'Completed'), ('O', 'Open'), ('F', 'Failed'), ('P', 'Pending')], max_length=50, null=True),
        ),
    ]
