# Generated by Django 3.2.12 on 2024-07-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0016_gamesscoreboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesscoreboard',
            name='played_games',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
