# Generated by Django 5.0.6 on 2024-07-25 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0017_gamesscoreboard_played_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestype',
            name='level',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
