# Generated by Django 3.2.12 on 2024-07-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0018_gamesscoreboard_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesscoreboard',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
